### PR TITLE
PROJECT: BUILDING WITH ACTIVE RECORD

### PR DESCRIPTION
**Pull request by bmuhamood**
This project puts your knowledge of active record, models, and associations to the tests. You will build an application similar to Reddit (called Micro-Reddit) where a user can create a post and add comments to it.   
Full task description: **https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails.**

### CODE REVIEW

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team 👋
Status: Changes Required ♻️

Great job so far! 👏🎉 Isn't it great to be able to create models in Rails? :blush: 
Let's cover a few details to make your project better ⏬

## Models
##### Post
- [x] `body` and `title` should be validated. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/postValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))

## README

- [x] Please change `How to run tests` into `How To Run This Application In Console`. Since this is not a test.

## Typos

💡 There are too many typos. Please fix all of them.

- [x] Branch name `devolop`  ➡️ Please fix 🚨
- [x] In Readme `Ordin Project`  ➡️ Please fix 🚨
- [x] Post attribute `tittle`  ➡️ Please fix 🚨

## General

- [ ]  :warning: Important: In your next project, initialize the rails in the development branch. And then branch out to your feature branch(give it a descriptive name please😇). And then you can make your actual changes in that branch.

- [ ]  Branch name `feature`. Okay, but, which feature? It should tell something about what we are doing 😇

- [ ] Pr message is currently copy/paste. It is a good practice to have a unique PR message.

- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

💡 Delete `node_modules` folder. Adding it to the .gitignore is the first step. But you should do one more thing to delete it from the repository.

### That's it, team! Please, after making the changes, you can request another code review 😇
With all my respect. 🙏

**Comment by balerum03** [comment]
We have fixed typos in the project and on future projects we are for sure using a more descriptive name for our feature branches.
Thanks for all your comments.

**Review by BrittanyBlake — APPROVED** [review]
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****



 Good Luck and Happy Coding! 🍀 👩🏾‍💻

**Comment by bmuhamood** [comment]
Thanks alot

**Pull request merged**
